ProductID:
  name: pid
  in: path
  schema:
    anyOf:
      - type: string
      - type: number
  required: true
  description: Product ID

CartID:
  name: cid
  in: path
  schema:
    anyOf:
      - type: string
      - type: number
  required: true
  description: Cart ID
