openapi: 3.0.3
info:
  title: E-ComMercy API
  version: beta 1.4.0
  description: |-
    Generic ecommerce API design for Backend course on Coderhouse
    _create by Allan Reynoso_
    [Github /AllanNara](https://github.com/AllanNara)
  contact:
    email: allannara@outlook.com
    name: Contact me
    url: https://www.linkedin.com/in/allannara
  license:
    name: MIT License
    url: https://github.com/AllanNara/PF-Backend/blob/main/LICENSE.txt
servers:
  - url: http://localhost:8080/api
    description: Local development API
tags:
  - name: products
    description: CRUD operations of products
  - name: carts
    description: CRUD operations of the user carts
security: []

paths:
  /products:
    $ref: paths/products/products.yaml
  /products/{pid}:
    $ref: paths/products/products-by-id.yaml
  /carts:
    $ref: paths/carts/carts.yaml
  /carts/{cid}:
    $ref: paths/carts/carts-by-id.yaml
  /carts/{cid}/product/{pid}:
    $ref: paths/carts/cart-product.yaml

components:
  schemas:
    Product:
      $ref: components/schemas/Product.yaml
    Pagination:
      $ref: components/schemas/Pagination.yaml
    Cart:
      $ref: components/schemas/Cart.yaml
    ErrorRequest:
      $ref: components/schemas/ErrorRequest.yaml
    SuccessRequest:
      $ref: components/schemas/SuccessRequest.yaml
  requestBodies:
    NewProduct:
      $ref: components/requestBodies/NewProduct.yaml
    UpdateProduct:
      $ref: components/requestBodies/UpdateProduct.yaml
    UpdateCart:
      $ref: components/requestBodies/UpdateCart.yaml
    UpdateCartProduct:
      $ref: components/requestBodies/UpdateCartProduct.yaml
  parameters:
    PaginationLimitQuery:
      $ref: components/parameters/Queries.yaml#/PaginationLimitQuery
    PaginationPageQuery:
      $ref: components/parameters/Queries.yaml#/PaginationPageQuery
    PaginationSortQuery:
      $ref: components/parameters/Queries.yaml#/PaginationSortQuery
    PaginationQueryQuery:
      $ref: components/parameters/Queries.yaml#/PaginationQueryQuery
    CartID:
      $ref: components/parameters/Params.yaml#/CartID
    ProductID:
      $ref: components/parameters/Params.yaml#/ProductID
  responses:
    PaginationRes:
      $ref: components/responses/PaginationRes.yaml
    SuccessfulCartOperation:
      $ref: components/responses/SuccessfulOperation.yaml#/SuccessfulCartOperation
    SuccessfulProductOperation:
      $ref: components/responses/SuccessfulOperation.yaml#/SuccessfulProductOperation
    CartOrProductNotFound:
      $ref: components/responses/ResourseNotFound.yaml#/CartOrProductNotFound
    CartNotFound:
      $ref: components/responses/ResourseNotFound.yaml#/CartNotFound
    ProductNotFound:
      $ref: components/responses/ResourseNotFound.yaml#/ProductNotFound
    MissingFieldsInProduct:
      $ref: components/responses/ErrorProductOperation.yaml#/MissingFieldsInProduct
    CodeAlreadyInUse:
      $ref: components/responses/ErrorProductOperation.yaml#/CodeAlreadyInUse
  examples:
    PaginationExample:
      $ref: components/examples/PaginationExample.yaml#/PaginationExample
    PaginationExampleMongo:
      $ref: components/examples/PaginationExample.yaml#/PaginationExampleMongo
