parameters:
  - $ref: '../../components/parameters/Params.yaml#/ProductID'

## READ ##
get:
  tags:
    - products
  operationId: getProductById
  summary: Get product by ID
  description: Return one product, find by ID
  responses:
    '200':
      $ref: ../../components/responses/products/SuccessOperationProduct.yaml#/SuccessfulGetProduct
    '404':
      $ref: ../../components/responses/products/ErrorProductOperation.yaml#/ProductNotFound

## UPDATE ##
put:
  tags:
    - products
  operationId: updateProduct
  summary: Update product
  description: Update properties of product, find by ID
  requestBody:
    $ref: ../../components/requestBodies/products/UpdateProduct.yaml
  responses:
    '200':
      $ref: ../../components/responses/products/SuccessOperationProduct.yaml#/SuccessfulPutProduct
    '404':
      $ref: ../../components/responses/products/ErrorProductOperation.yaml#/ProductNotFound

## DELETE ##
delete:
  tags:
    - products
  operationId: deleteProduct
  summary: Delete product
  description: Delete product by ID
  responses:
    '200':
      $ref: ../../components/responses/products/SuccessOperationProduct.yaml#/SuccessfulDeleteProduct
    '404':
      $ref: ../../components/responses/products/ErrorProductOperation.yaml#/ProductNotFound
