## READ ##
get:
  parameters:
    - $ref: '../../components/parameters/Queries.yaml#/PaginationLimitQuery'
    - $ref: '../../components/parameters/Queries.yaml#/PaginationPageQuery'
    - $ref: '../../components/parameters/Queries.yaml#/PaginationSortQuery'
    - $ref: '../../components/parameters/Queries.yaml#/PaginationQueryQuery'

  tags:
    - products
  operationId: getProducts
  summary: Get products
  description: Retun all products
  responses:
    '200':
      $ref: ../../components/responses/products/PaginationRes.yaml
    '500':
      $ref: ../../components/responses/Default.yaml

## CREATE ##
post:
  tags:
    - products
  operationId: addProduct
  summary: Add product
  description: Add new product with unique code
  requestBody:
    $ref: ../../components/requestBodies/products/NewProduct.yaml
  responses:
    '200':
      $ref: ../../components/responses/products/SuccessOperationProduct.yaml#/SuccessfulPostProduct
    '400':
      $ref: ../../components/responses/products/ErrorProductOperation.yaml#/MissingFieldsInProduct
    '409':
      $ref: ../../components/responses/products/ErrorProductOperation.yaml#/CodeAlreadyInUse
