get:
  parameters:
    - $ref: '../../components/parameters/queries.yaml#/paginationLimitQuery'
    - $ref: '../../components/parameters/queries.yaml#/paginationPageQuery'
    - $ref: '../../components/parameters/queries.yaml#/paginationSortQuery'
    - $ref: '../../components/parameters/queries.yaml#/paginationQueryQuery'
  tags:
    - products
  operationId: getProducts
  summary: Get products
  description: Retun all products
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/Pagination.yaml'
    '400':
      description: Page not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                default: error
              message:
                type: string
                default: Query 'page' is not valid
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string

post:
  tags:
    - products
  operationId: addProduct
  summary: Add product
  description: Add new product with unique code
  requestBody:
    $ref: ../../components/requestBodies/new-product.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                default: success
              payload:
                allOf:
                  - $ref: ../../components/schemas/Product.yaml
                  - type: object
                    properties:
                      id:
                        anyOf:
                          - type: string
                          - type: integer
    '400':
      description: Missing fields
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                default: error
              message:
                type: string
                example: Missing fields
    '409':
      description: Code alredy in use
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                default: error
              message:
                type: string
                example: Code alredy exists
